-- 0001 · Catàleg de cims (docs/03-modelo-datos.md §1.1)
--
-- Lectura pública (anon + authenticated) amb RLS; cap política d'escriptura: només el
-- `service_role` (que salta la RLS) hi escriu, des del script de seed a partir dels fitxers
-- versionats `src/lib/data/catalog/*.json` (font de veritat del catàleg).
-- Identificadors en català sense accents, com al domini (`src/lib/domain/types.ts`).

create extension if not exists postgis with schema extensions;

-- ---------------------------------------------------------------------------------------------
-- Tipus
-- ---------------------------------------------------------------------------------------------

create type public.ambit as enum ('catalunya', 'andorra', 'catalunya_nord');
create type public.estat_revisio as enum ('esborrany', 'revisat');
create type public.lang as enum ('ca', 'es');
create type public.confianca as enum ('alta', 'mitjana', 'baixa');
create type public.font_dada as enum (
	'feec_pdf_essencials', -- llista pública d'essencials (PDF de la FEEC)
	'icgc',                -- Geocodificador ICGC / Nomenclàtor (CC BY 4.0)
	'icgc_mdt',            -- Model d'elevacions MET-5 de l'ICGC (CC BY 4.0)
	'ign',                 -- IGN France, geocodificació BD TOPO (Licence Ouverte 2.0)
	'ign_alti',            -- IGN France, RGE ALTI (Licence Ouverte 2.0)
	'osm',                 -- OpenStreetMap (ODbL 1.0)
	'wikidata',            -- Wikidata (CC0)
	'manual'               -- resolució manual documentada (camp `nota` obligatori)
);

create or replace function public.tocar_updated_at() returns trigger
language plpgsql as $$
begin
	new.updated_at := now();
	return new;
end;
$$;

-- ---------------------------------------------------------------------------------------------
-- Comarques i zones (comarques FEEC + Andorra + Catalunya Nord) — `comarques.json`
-- ---------------------------------------------------------------------------------------------

create table public.comarques (
	id smallint generated by default as identity primary key,
	ambit public.ambit not null,
	codi_icgc smallint unique check (codi_icgc between 1 and 99), -- null fora de Catalunya
	nom_ca text not null,
	nom_es text not null,
	nom_amb_article_ca text not null,  -- "l'Alt Camp", "el Bages", "Osona"
	nom_amb_de_ca text not null,       -- "de l'Alt Camp", "del Bages", "d'Osona"
	slug_ca text not null unique check (slug_ca ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
	slug_es text not null unique check (slug_es ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
	geom extensions.geography(MultiPolygon, 4326), -- límit (ICGC CC BY / IGN); opcional
	updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------------------------
-- Cims — `cims.json`
-- ---------------------------------------------------------------------------------------------

create table public.cims (
	id smallint primary key,                      -- id estable propi (1..n); mai no es reutilitza
	nom_oficial text not null,                    -- tal com surt a la llista de la FEEC
	nom_ca text not null,                         -- nom visible/popular (H1): "Pedraforca"
	nom_es text,                                  -- null = igual que ca
	nom_amb_article_ca text not null,             -- "el Pedraforca"
	nom_amb_de_ca text not null,                  -- "del Pedraforca"
	toponim text,                                 -- topònim a la font geogràfica (ICGC/IGN...)
	slug_ca text not null unique check (slug_ca ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
	slug_es text not null unique check (slug_es ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
	comarca_id smallint not null references public.comarques (id), -- assignada per la FEEC
	altitud_m smallint not null check (altitud_m between 0 and 3200),
	essencial boolean not null default false,
	geom extensions.geography(Point, 4326),       -- null fins que estigui verificada
	coord_precisio_m smallint check (coord_precisio_m >= 0),
	confianca public.confianca not null default 'baixa',
	estat_revisio public.estat_revisio not null default 'esborrany',
	actiu boolean not null default true,
	retirat_at date,                              -- si la FEEC la treu de la llista
	cataleg_versio text not null,                 -- p. ex. '2026-09-essencials'
	updated_at timestamptz not null default now(),
	check (actiu or retirat_at is not null)
);

create index cims_geom_idx on public.cims using gist (geom);
create index cims_comarca_idx on public.cims (comarca_id);
create index cims_essencial_idx on public.cims (essencial) where essencial;

create table public.cim_alias (
	cim_id smallint not null references public.cims (id) on delete cascade,
	nom text not null,
	lang public.lang,                             -- null = qualsevol idioma
	primary key (cim_id, nom)
);

create table public.slug_redireccions (
	id bigint generated always as identity primary key,
	lang public.lang not null,
	slug_antic text not null,
	cim_id smallint references public.cims (id) on delete cascade,
	comarca_id smallint references public.comarques (id) on delete cascade,
	created_at timestamptz not null default now(),
	unique (lang, slug_antic),
	check ((cim_id is null) <> (comarca_id is null))
);

-- ---------------------------------------------------------------------------------------------
-- Procedència camp a camp ("deixar constància de la font")
-- ---------------------------------------------------------------------------------------------

create table public.fonts_dades (
	id bigint generated always as identity primary key,
	entitat text not null check (entitat in ('cim', 'comarca', 'ruta', 'restriccio')),
	entitat_id integer not null,
	camp text not null,                           -- 'nom', 'coordenades', 'altitud', 'essencial'...
	font public.font_dada not null,
	ref text,                                     -- id OSM, Qid, cleabs IGN, topònim ICGC...
	url text check (url is null or url ~ '^https://'),
	llicencia text,                               -- 'CC BY 4.0', 'ODbL 1.0', 'CC0', 'LO 2.0'
	obtingut_at date,
	nota text,
	check (font <> 'manual' or nota is not null),
	unique (entitat, entitat_id, camp, font)
);

create index fonts_dades_entitat_idx on public.fonts_dades (entitat, entitat_id);

-- ---------------------------------------------------------------------------------------------
-- Restriccions d'accés
-- ---------------------------------------------------------------------------------------------

create table public.restriccions_acces (
	id bigint generated always as identity primary key,
	cim_id smallint not null references public.cims (id) on delete cascade,
	tipus text not null check (tipus in ('fauna', 'obres', 'propietat', 'militar', 'altres')),
	periode_inici_mmdd char(5) check (periode_inici_mmdd ~ '^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'),
	periode_fi_mmdd char(5) check (periode_fi_mmdd ~ '^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'),
	data_inici date,
	data_fi date,
	font_url text not null check (font_url ~ '^https://'),
	verificat_at date not null,
	vigent boolean not null default true,
	check ((periode_inici_mmdd is null) = (periode_fi_mmdd is null)),
	check (data_inici is null or data_fi is null or data_inici <= data_fi)
);

create index restriccions_cim_idx on public.restriccions_acces (cim_id);

-- ---------------------------------------------------------------------------------------------
-- Rutes d'accés i continguts traduïbles (s'ompliran en fases posteriors)
-- ---------------------------------------------------------------------------------------------

create table public.rutes (
	id bigint generated always as identity primary key,
	cim_id smallint not null references public.cims (id) on delete cascade,
	es_normal boolean not null default false,
	sortida_nom text,
	sortida_geom extensions.geography(Point, 4326),
	desnivell_pos_m integer check (desnivell_pos_m >= 0),
	distancia_km numeric(5, 2) check (distancia_km >= 0),
	temps_min integer check (temps_min > 0),
	mide_medi smallint check (mide_medi between 1 and 5),
	mide_itinerari smallint check (mide_itinerari between 1 and 5),
	mide_desplacament smallint check (mide_desplacament between 1 and 5),
	mide_esforc smallint check (mide_esforc between 1 and 5),
	estat public.estat_revisio not null default 'esborrany',
	updated_at timestamptz not null default now()
);

create unique index rutes_una_normal_idx on public.rutes (cim_id) where es_normal;

create table public.ruta_enllacos (
	id bigint generated always as identity primary key,
	ruta_id bigint not null references public.rutes (id) on delete cascade,
	url text not null check (url ~ '^https://'),
	titol text,
	font text,
	lang public.lang
);

create table public.continguts (
	id bigint generated always as identity primary key,
	entitat text not null check (entitat in ('cim', 'comarca', 'ruta', 'guia')),
	entitat_id integer not null,
	camp text not null check (camp in ('descripcio', 'intro', 'titol_seo', 'meta_descripcio', 'acces')),
	lang public.lang not null,
	text text not null,
	estat public.estat_revisio not null default 'esborrany',
	generat_per text not null check (generat_per in ('ia', 'huma')),
	model_ia text,
	revisat_per text,
	revisat_at timestamptz,
	updated_at timestamptz not null default now(),
	unique (entitat, entitat_id, camp, lang),
	check (estat = 'esborrany' or (revisat_per is not null and revisat_at is not null))
);

create table public.contingut_fonts (
	contingut_id bigint not null references public.continguts (id) on delete cascade,
	url text not null check (url ~ '^https://'),
	titol text,
	consultat_at date,
	llicencia text,
	primary key (contingut_id, url)
);

-- ---------------------------------------------------------------------------------------------
-- updated_at automàtic
-- ---------------------------------------------------------------------------------------------

create trigger comarques_updated_at before update on public.comarques
	for each row execute function public.tocar_updated_at();
create trigger cims_updated_at before update on public.cims
	for each row execute function public.tocar_updated_at();
create trigger rutes_updated_at before update on public.rutes
	for each row execute function public.tocar_updated_at();
create trigger continguts_updated_at before update on public.continguts
	for each row execute function public.tocar_updated_at();

-- ---------------------------------------------------------------------------------------------
-- RLS: lectura pública, escriptura només service_role
-- ---------------------------------------------------------------------------------------------

alter table public.comarques enable row level security;
alter table public.cims enable row level security;
alter table public.cim_alias enable row level security;
alter table public.slug_redireccions enable row level security;
alter table public.fonts_dades enable row level security;
alter table public.restriccions_acces enable row level security;
alter table public.rutes enable row level security;
alter table public.ruta_enllacos enable row level security;
alter table public.continguts enable row level security;
alter table public.contingut_fonts enable row level security;

create policy "lectura publica" on public.comarques for select to anon, authenticated using (true);
create policy "lectura publica" on public.cims for select to anon, authenticated using (true);
create policy "lectura publica" on public.cim_alias for select to anon, authenticated using (true);
create policy "lectura publica" on public.slug_redireccions for select to anon, authenticated using (true);
create policy "lectura publica" on public.fonts_dades for select to anon, authenticated using (true);
create policy "lectura publica" on public.restriccions_acces for select to anon, authenticated using (true);
-- Rutes i textos: només el que està revisat és públic.
create policy "lectura publica revisat" on public.rutes for select to anon, authenticated
	using (estat = 'revisat');
create policy "lectura publica revisat" on public.ruta_enllacos for select to anon, authenticated
	using (exists (select 1 from public.rutes r where r.id = ruta_id and r.estat = 'revisat'));
create policy "lectura publica revisat" on public.continguts for select to anon, authenticated
	using (estat = 'revisat');
create policy "lectura publica revisat" on public.contingut_fonts for select to anon, authenticated
	using (exists (select 1 from public.continguts c where c.id = contingut_id and c.estat = 'revisat'));

grant usage on schema public to anon, authenticated;
grant select on
	public.comarques, public.cims, public.cim_alias, public.slug_redireccions, public.fonts_dades,
	public.restriccions_acces, public.rutes, public.ruta_enllacos, public.continguts,
	public.contingut_fonts
	to anon, authenticated;
revoke insert, update, delete, truncate on
	public.comarques, public.cims, public.cim_alias, public.slug_redireccions, public.fonts_dades,
	public.restriccions_acces, public.rutes, public.ruta_enllacos, public.continguts,
	public.contingut_fonts
	from anon, authenticated;
